### ISSUE TITLE
how to do simple assert?

### ISSUE THREAD

**Issue by mgutz** [go-check/check#18]
Is there a way to do this?

```
c.Assert(found.Id > 0)
```

I have many checks like this 

```
c.Assert(found.Id > 0, Equals, true)
```

**Comment by exklamationmark** [comment]
i don't think the library provides this right now, as there's no 'IsTrue' checker that 's implemented in https://github.com/go-check/check/blob/v1/checkers.go

If you might really use it allot, it might be worthwile to modify the Assert & Check function so that by default it checks if the expression is true

**Comment by mgutz** [comment]
thanks
